[build]
  command = "npm run build"
  functions = "function"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/function/*"
  to = "/function/:splat"
  headers = { Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE", Access-Control-Allow-Headers = "Content-Type" }

