[build]
  command = "npm run build"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-core"

[[plugins]]
  package = "@netlify/plugin-functions-build"
